services:
  genesis-core:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 3000:3000
    restart: always
    environment:
      - NODE_ENV=production
    networks:
      - genesis_network

  surrealdb:
    image: surrealdb/surrealdb:latest
    container_name: genesis_surrealdb
    user: root
    command: start --user root --pass root --bind 0.0.0.0:8000 rocksdb:/data/genesis.db
    ports:
      - "8000:8000"
    volumes:
      - ./surrealdata:/data # Mapăm un folder local pentru persistență (opțional)
    restart: always

networks:
  genesis_network:
    driver: bridge